### ISSUE TITLE
👽 Emoji request

### ISSUE THREAD

**Issue by marc2332** [LucasCtrl/SpookyBot#17]
## Emoji request

**Emoji: 👽**
**Potential ID(s): monster, alien**
**Potential trigger(s): monster, alien**

**Comment by LucasCtrl** [comment]
Emoji introduced in revision [2c647bb](https://github.com/LucasCtrl/SpookyBot/wiki/i18n/2c647bbb2eb42dfe96ca14a05ace18a0e85aecaa)
